version: "3"
services:
  api:
    container_name: somnifero_dev
    build:
      context: .
      dockerfile: dockerfile.dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5000
    volumes:
      - .:/app
    ports:
      - 5000:5000
    links: 
      - mongodb:database
    depends_on:
      - mongodb
  mongodb:
    image: mongo:4
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
volumes:
  mongodata:
    driver: local
